export {
  copyAIPrompt,
  getAIPrompt,
  getOptions,
  scan,
  setOptions,
  stop,
  getSessionData,
  getWastedStats,
  getLeakedComponents,
  getDetachedComponents,
  getOnPushCandidates,
  getReferentialInstability,
  getZonePollutionEvents,
  getCdGraph,
  getSignalDependencyGraph,
  getComponentCostAnalysis,
  beginInteraction,
  endInteraction,
  getInteractionReport,
  setInteractionBaseline,
  compareWithInteractionBaseline,
  compareInteractionReports,
  createInteractionReport,
  formatInteractionReportMarkdown,
  formatInteractionReportHtml
} from './application/runtime';
export {
  AngularRenderScanMarkDirective,
  ANGULAR_RENDER_SCAN_OPTIONS,
  provideAngularRenderScan,
  restoreApplicationRef
} from './infrastructure/angular/angular';
export type {
  AngularRenderChangedInput,
  AngularRenderCycle,
  AngularRenderEntry,
  AngularRenderReason,
  AngularRenderScanOptions,
  AngularRenderScanBudgets,
  BudgetViolation,
  SessionExportData,
  WaterfallEntry,
  WastedStats,
  AngularRenderMutationType,
  CdTriggerAttribution,
  CdTriggerSource,
  OnPushCandidate,
  ReferentialInstabilityReport,
  ZonePollutionEvent,
  ZonePollutionEvent as ZonePollutionEventType,
  CdGraph,
  CdGraphNode,
  CdGraphEdge,
  SignalDependencyGraph,
  ComponentCostEntry,
  InteractionFinding,
  InteractionFindingKind,
  InteractionFindingSeverity,
  InteractionMetrics,
  InteractionReport,
  InteractionMetricDelta,
  InteractionComparison
} from './domain/entities';
export { startRenderAudit } from './testing';
export type { RenderAuditReport, RenderAuditSession } from './testing';
